export const hostessTexts = [
    {en: 'Hosted event', hu: 'Esemény'},
    {en: 'Ask a question from the Hostess', hu: 'Tegyél fel egy kérdést a Hostessnek'},
    {en: 'Answer by the Hostess', hu: 'A Hostess válasza'},
    {en: 'New Question', hu: 'Új Kérdés'},
    {en: 'Add Instruction', hu: 'Utasítás Hozzáadása'},
    {en: 'View Instructions', hu: 'Utasítások Átnézése'},
    {en: 'Submit', hu: 'Elküld'},
    {en: 'Enter your question (8 - 80 characters)', hu: 'Írd be a kérdésed (8 - 80 karakterben)'},
    {en: 'Provide additional info for the Hostess', hu: 'Adj további információt a Hostessnek'},
    {en: 'Enter the info (30 - 300 characters)', hu: 'Írd be az információt (30 - 300 karakter)'},
    {en: 'Submit Info', hu: 'Info Beküldése'},
    {en: 'Cancel', hu: 'Mégsem'},
    {en: 'Back', hu: 'Vissza'},
    {en: 'Do you want to delete this instruction', hu: 'Törölni akarod ezt az utasítást'},
    {en: 'Yes', hu: 'Igen'},
    {en: 'No', hu: 'Nem'},
    {en: 'filter text', hu: 'szöveg szűrése'},
    {en: '', hu: ''},
]