export const translatedTexts = [
    {en: 'Home', hu: 'Főoldal'},
    {en: 'AI Barchoba Game', hu: 'AI Barkóba Játék'},
    {en: 'Question', hu: 'Kérdés'},
    {en: 'Answer', hu: 'Válasz'},
    {en: 'Guess', hu: 'Tipp'},
    {en: 'Send Question', hu: 'Kérdés Küldése'},
    {en: 'Next Question', hu: 'Következő Kérdés'},
    {en: 'I give up', hu: 'Szabad a gazda'},
    {en: 'Final Guess', hu: 'Rákérdezek'},
    {en: 'Start a New Game', hu: 'Új Játék Indítása'},
    {en: 'Loading the Barchoba Game', hu: 'Barkóba játék betöltése'},
    {en: 'Enter your question (4-40 characters)', hu: 'Írd be a kérdésed (4-40 karakter)'},
    {en: 'back to questions', hu: 'kérdezek még'},
    {en: 'Congrats, you solved it from', hu: 'Gratulálok, kitaláltad'},
    {en: 'questions', hu: 'kérdésből'},
    {en: 'The solution was', hu: 'A megoldás'},
    {en: 'You have exited the game', hu: 'Kiléptél a játékból'},
    {en: 'Do you really want to exit from this game?', hu: 'Valóban ki szeretnél lépni a játékból?'},
    {en: 'Yes', hu: 'Igen'},
    {en: 'No', hu: 'Nem'},
    {en: 'Yes.', hu: 'Igen.'},
    {en: 'No.', hu: 'Nem.'},
]