export const translatedTexts = [
    {en: 'Home', hu: 'Főoldal'},
    {en: 'AI Barkochba Game', hu: 'AI Barkochba Játék'},
    {en: 'Question', hu: 'Kérdés'},
    {en: 'Answer', hu: 'Válasz'},
    {en: 'Guess', hu: 'Tipp'},
    {en: 'Send', hu: 'Küldés'},
    {en: 'Next', hu: 'Következő'},
    {en: 'Send Guess', hu: 'Tipp Küldése'},
    {en: 'I give up', hu: 'Szabad a gazda'},
    {en: 'Final Guess', hu: 'Rákérdezek'},
    {en: 'Start a New Game', hu: 'Új Játék Indítása'},
    {en: 'Show Leaderboard', hu: 'Eredménytábla'},
    {en: 'Leaderboard', hu: 'Eredménytábla'},
    {en: 'Loading the Barkochba Game', hu: 'Barkochba játék betöltése'},
    {en: 'Enter your question (3-40 characters)', hu: 'Írd be a kérdésed (3-40 karakter)'},
    {en: 'back to questions', hu: 'kérdezek még'},
    {en: 'Enter the name', hu: 'Írd be a nevet'},
    {en: 'Congrats, you solved it from', hu: 'Gratulálok, kitaláltad'},
    {en: 'questions', hu: 'kérdésből'},
    {en: 'The solution was', hu: 'A megoldás'},
    {en: 'I cannot answer.', hu: 'Nem válaszolhatok.'},
    {en: 'You have exited the game', hu: 'Kiléptél a játékból'},
    {en: 'Do you really want to exit from this game?', hu: 'Valóban ki szeretnél lépni a játékból?'},
    {en: 'Yes', hu: 'Igen'},
    {en: 'No', hu: 'Nem'},
    {en: 'Yes.', hu: 'Igen.'},
    {en: 'No.', hu: 'Nem.'},
    {en: 'Cancel', hu: 'Mégsem'},
    {en: 'Submit', hu: 'Elküld'},
    {en: "The model is not responding. Proceed with another question.", hu: "A modell nem válaszol. Folytasd egy másik kérdéssel."},
    {en: "The model is not responding. Please, try again.", hu: "A modell nem válaszol. Kérlek, próbáld újra."},
    {en: 'Competition', hu: 'Verseny'},
    {en: 'Player', hu: 'Játékos'},
    {en: 'Solution', hu: 'Megoldás'},
    {en: '3-10 characters', hu: '3-10 karakter'},
    {en: 'Please, enter <strong>your (nick)name</strong> to post your result to the leaderboard:', 
        hu: 'Kérlek, add meg a <strong>(bece)neved</strong>, hogy kiírhassuk az eredménytáblára'},
]